### ISSUE TITLE
adafruit_wiznet5K.py의 주석 변경요청

### ISSUE THREAD

**Issue by irinakim12** [bjnhur/pico-W5500#1]
![image](https://user-images.githubusercontent.com/9648281/130372832-4da0da04-07cc-4beb-8b76-f700a7a58598.png)
W5100S의 레지스터 매핑이 되어있으나, W5500으로 표시되어있어요.

**Comment by bjnhur** [comment]
Hey @irinakim12, modify the comment in 598736d. Close this issue #1
